
[font]
size = 8

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window.padding]
x = 6
y = 6

[general]
import = ["/home/gideon/.cache/wal/alacrittycolors.yml"]
